nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8100']
            allow_headers: ['origin', 'content-type', 'authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
